const TYPE_WEIGHTS={person_candidate:.35,account:.15,organisation_candidate:.15,location_candidate:.10,email:.10,phone:.05};
const QUALITY={"linkedin.com":.90,"facebook.com":.70,"instagram.com":.70,"x.com":.65,"twitter.com":.65,"tiktok.com":.65,"youtube.com":.70,"imdb.com":.80};
function norm(v){return String(v||"").replace(/\s+/g," ").trim().toLowerCase();}
function tokens(v){return norm(v).split(/\s+/).filter(Boolean).filter(x=>x!=="bin"&&x!=="binti");}
function similarity(a,b){const x=tokens(a),y=tokens(b);if(!x.length||!y.length)return 0;const overlap=x.filter(t=>y.includes(t)).length;return Number(Math.min(1,(overlap/Math.max(x.length,y.length))*.75+(x.at(-1)===y.at(-1)?.15:0)).toFixed(4));}
function hostQuality(url){try{return QUALITY[new URL(url).hostname.toLowerCase().replace(/^www\./,"")]||.55;}catch{return .50;}}
function scoreEvidence({subject,entity}){const sim=similarity(entity.value,subject),exact=norm(entity.value)===norm(subject),sources=entity.sources||[],independent=Math.min(1,sources.length/3),quality=sources.length?sources.reduce((sum,s)=>sum+hostQuality(s.url),0)/sources.length:.5;const typeWeight=TYPE_WEIGHTS[entity.type]||.05;return Number(Math.min(1,sim*.35+(exact?.15:0)+independent*.20+quality*.15+typeWeight*.15).toFixed(4));}
function assessCandidate({subject,person,accounts=[],organisations=[],locations=[]}){const nameExact=norm(person.value)===norm(subject),nameSimilarity=similarity(person.value,subject);const accountLinks=accounts.filter(a=>similarity(person.value,a.username||a.value)>=.25);const orgLinks=organisations.filter(o=>o.sources?.some(s=>person.sources?.some(p=>p.url===s.url)));const locationLinks=locations.filter(l=>l.sources?.some(s=>person.sources?.some(p=>p.url===s.url)));const dimensions={name:Number((nameExact?.95:nameSimilarity).toFixed(4)),accounts:Number(Math.min(1,accountLinks.length*.35).toFixed(4)),organisations:Number(Math.min(1,orgLinks.length*.30).toFixed(4)),locations:Number(Math.min(1,locationLinks.length*.20).toFixed(4)),sourceIndependence:Number(Math.min(1,(person.sources?.length||0)/3).toFixed(4))};const corroborated=[dimensions.accounts,dimensions.organisations,dimensions.locations].filter(v=>v>0).length;let confidence=dimensions.name*.55+dimensions.sourceIndependence*.20+Math.max(dimensions.accounts,dimensions.organisations,dimensions.locations)*.25;if(!nameExact)confidence*=.88;if(corroborated===0&&dimensions.sourceIndependence>=.8)confidence=Math.min(confidence,.50);confidence=Number(Math.min(1,confidence).toFixed(4));const reasons=[];if(nameExact)reasons.push("Exact name match");else if(nameSimilarity>=.5)reasons.push("Strong name similarity");else reasons.push("Partial name similarity");if(person.sources?.length)reasons.push(`${person.sources.length} distinct source${person.sources.length===1?"":"s"}`);if(accountLinks.length)reasons.push(`${accountLinks.length} account signal${accountLinks.length===1?"":"s"} linked to candidate`);if(orgLinks.length)reasons.push(`${orgLinks.length} organisation signal${orgLinks.length===1?"":"s"} corroborated`);if(locationLinks.length)reasons.push(`${locationLinks.length} location signal${locationLinks.length===1?"":"s"} corroborated`);if(corroborated===0)reasons.push("No independent identity attribute corroborated");return{confidence,level:confidence>=.80?"high":confidence>=.60?"moderate":"low",dimensions,reasons};}
export {scoreEvidence,assessCandidate,similarity,hostQuality};
