import { extractEntityCandidates, extractTitle, extractReadableText } from "./index.js";
import { search } from "./search.js";

const LIMITS={maxSearchResults:5,maxPages:5,maxDepth:2,maxSearchRequests:5,maxCandidates:10,maxSourcesPerCandidate:10};
const PROFILE_HOSTS={"linkedin.com":"LinkedIn","my.linkedin.com":"LinkedIn","facebook.com":"Facebook","instagram.com":"Instagram","x.com":"X","twitter.com":"X","tiktok.com":"TikTok","youtube.com":"YouTube"};
const NOISE=new Set(["join","facebook","explore","email","password","log","bahasa","indonesia","messenger","lite","meta","photos","friends","connect","account","create","sign","up","home","about","contact","privacy","policy","terms","official","website","career","careers","business","commercial","division","head","executive","general","manager","profile","page","directory","malaysia","selangor"]);

function normalize(v){return String(v||"").replace(/\s+/g," ").trim().toLowerCase();}
function tokens(v){return normalize(v).split(/\s+/).filter(x=>x&&x!=="bin"&&x!=="binti");}
function cleanUrl(url){try{const u=new URL(url);for(const k of ["utm_source","utm_medium","utm_campaign","utm_term","utm_content","msclkid"])u.searchParams.delete(k);return u.toString();}catch{return String(url||"");}}
function nameVariant(a,b){const x=tokens(a),y=tokens(b);if(!x.length||!y.length)return 0;const overlap=x.filter(t=>y.includes(t)).length;const coverage=overlap/Math.max(x.length,y.length);const surname=x.at(-1)===y.at(-1)?0.15:0;return Math.min(1,coverage*0.75+surname);}
function likelyPerson(value,seed){const raw=String(value||"").trim(),ts=tokens(raw);if(ts.length<2||ts.length>5||raw.length>80)return false;if(ts.some(t=>NOISE.has(t)))return false;const st=tokens(seed);return !st.length||ts.some(t=>st.includes(t));}
function accountFromUrl(url,title=""){try{const u=new URL(url),host=u.hostname.toLowerCase().replace(/^www\./,""),platform=PROFILE_HOSTS[host];if(!platform)return null;const p=u.pathname.split("/").filter(Boolean);let username=null;if(platform==="LinkedIn")username=p[0]==="in"?p[1]:null;else if(platform==="YouTube")username=p[0]?.startsWith("@")?p[0].slice(1):(["channel","user","c"].includes(p[0]?.toLowerCase())?p[1]:null);else username=p[0]?.startsWith("@")?p[0].slice(1):p[0];if(!username||["home","search","explore","login","signup","settings","directory","feed"].includes(username.toLowerCase()))return null;return{type:"account",platform,username,value:`${platform}: ${username}`,normalized:`${platform}:${username}`.toLowerCase(),confidence:normalize(title).includes(normalize(username))?.9:.75,url:cleanUrl(url)};}catch{return null;}}
function extractSearchEntities(result){const text=`${result.title||""}. ${result.snippet||""}`;const entities=extractEntityCandidates(text).filter(e=>e.type!=="person_candidate"||likelyPerson(e.value,result.title||""));const account=accountFromUrl(result.url,result.title||"");if(account)entities.push(account);return entities;}
async function readPage(url){try{const target=new URL(url);if(!["http:","https:"].includes(target.protocol))throw new Error("Unsupported protocol");const r=await fetch(target.toString(),{headers:{"User-Agent":"Mozilla/5.0 (compatible; FreeOSINTExplorer/1.0)"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const html=await r.text(),text=extractReadableText(html);return{ok:true,url:cleanUrl(target.toString()),title:extractTitle(html),textLength:text.length,entities:extractEntityCandidates(text),text};}catch(error){return{ok:false,url,error:error.message||"Fetch failed"};}}
function sourceKey(s){return cleanUrl(s.url);}
function addEvidence(e,source,subject,store){if(!e?.type||!e?.value)return;const key=`${e.type}:${normalize(e.normalized||e.value)}`;let x=store.get(key);if(!x){x={...e,value:e.value,normalized:normalize(e.normalized||e.value),sources:[],sourceCount:0};store.set(key,x);}if(!x.sources.some(s=>s.url===source.url)){x.sources.push({title:source.title||"",url:source.url,read:!!source.read});x.sourceCount++;}if(e.confidence>x.confidence)x.confidence=e.confidence;}
function scoreEntity(e,subject){const name=nameVariant(e.value,subject),exact=normalize(e.value)===normalize(subject)?1:0,multi=Math.min(1,e.sourceCount/3);return Number(Math.min(1,e.confidence*.35+name*.3+multi*.25+exact*.1).toFixed(4));}
function collectCandidates(entityMap,subject){const people=[...entityMap.values()].filter(e=>e.type==="person_candidate").map(e=>({...e,score:scoreEntity(e,subject)}));const accounts=[...entityMap.values()].filter(e=>e.type==="account").map(e=>({...e,score:scoreEntity(e,subject)}));
  const candidates=[];
  for(const person of people){const candidate={id:`person-${candidates.length+1}`,name:person.value,confidence:person.score,signals:{name:person.value,accounts:[],organisations:[],locations:[]},sources:[...person.sources]};for(const a of accounts){const usernameScore=nameVariant(person.value,a.username);if(usernameScore>=.25||a.sourceCount>1){candidate.signals.accounts.push({platform:a.platform,username:a.username,confidence:Number(Math.min(1,usernameScore*.7+a.sourceCount*.1).toFixed(4)),sources:a.sources.slice(0,3)});candidate.sources.push(...a.sources);candidate.confidence=Math.max(candidate.confidence,Number(Math.min(1,person.score*.6+usernameScore*.25+a.confidence*.15).toFixed(4)));}}candidate.sources=[...new Map(candidate.sources.map(s=>[s.url,s])).values()].slice(0,LIMITS.maxSourcesPerCandidate);candidates.push(candidate);}
  for(const a of accounts.filter(a=>!candidates.some(c=>c.signals.accounts.some(x=>x.platform===a.platform&&normalize(x.username)===normalize(a.username))))){candidates.push({id:`account-${candidates.length+1}`,name:null,confidence:scoreEntity(a,subject),signals:{name:null,accounts:[{platform:a.platform,username:a.username,confidence:a.score,sources:a.sources.slice(0,3)}],organisations:[],locations:[]},sources:a.sources.slice(0,LIMITS.maxSourcesPerCandidate)});}
  return candidates.sort((a,b)=>b.confidence-a.confidence).slice(0,LIMITS.maxCandidates);
}
function mergeRelated(entityMap,subject){const out={organisations:[],locations:[],emails:[],phones:[]};for(const e of entityMap.values()){if(e.type==="organisation_candidate"||e.type==="location_candidate"||e.type==="email"||e.type==="phone"){out[{organisation_candidate:"organisations",location_candidate:"locations",email:"emails",phone:"phones"}[e.type]].push({value:e.value,confidence:scoreEntity(e,subject),sources:e.sources.slice(0,3)});}}for(const k of Object.keys(out))out[k].sort((a,b)=>b.confidence-a.confidence).splice(10);return out;}
function buildPivotQueries(subject,entities){const queries=[],seen=new Set();const add=q=>{if(!seen.has(normalize(q))){seen.add(normalize(q));queries.push(q);}};for(const e of entities.filter(x=>x.type==="account").slice(0,2))add(`"${subject}" ${e.platform}`);for(const e of entities.filter(x=>x.type==="organisation_candidate").slice(0,2))add(`"${subject}" "${e.value}"`);return queries.slice(0,3);}

async function investigateQuery(query,state,env,provider,depth){if(state.visited.has(normalize(query))||state.searchRequests>=LIMITS.maxSearchRequests)return;state.visited.add(normalize(query));state.searchRequests++;let data;try{data=await search(query,env,provider);}catch(error){state.skippedSearches.push({query,depth,reason:error.message||"Search failed"});return;}const results=(data.results||[]).slice(0,LIMITS.maxSearchResults);for(const result of results){const source={title:result.title||"Search result",url:cleanUrl(result.url),read:false};for(const e of extractSearchEntities(result))addEvidence(e,source,state.subject,state.entities);if(state.pagesRead>=LIMITS.maxPages)break;const page=await readPage(result.url);state.pagesRead++;if(!page.ok){state.failed.push({title:result.title||"",url:result.url,reason:page.error});continue;}const ps={title:page.title||result.title||"",url:page.url,read:true};for(const e of page.entities.filter(e=>e.type!=="person_candidate"||likelyPerson(e.value,page.title)))addEvidence(e,ps,state.subject,state.entities);const account=accountFromUrl(page.url,page.title);if(account)addEvidence(account,ps,state.subject,state.entities);state.sources.set(page.url,{title:ps.title,url:ps.url,status:200,textLength:page.textLength,searchResult:true,read:true});}state.history.push({query,depth,resultCount:results.length});}

async function investigate(request,env){const url=new URL(request.url),subject=url.searchParams.get("q")?.trim();if(!subject)return Response.json({status:"error",error:"Missing search query",usage:"/investigate?q=Name"},{status:400});const provider=url.searchParams.get("provider")?.trim().toLowerCase()||null;const depth=Math.max(0,Math.min(LIMITS.maxDepth,Number.parseInt(url.searchParams.get("depth")||"1",10)||0));const state={subject,visited:new Set(),searchRequests:0,pagesRead:0,entities:new Map(),sources:new Map(),failed:[],skippedSearches:[],history:[]};const started=Date.now();await investigateQuery(subject,state,env,provider,0);for(let d=1;d<=depth&&state.searchRequests<LIMITS.maxSearchRequests;d++){const pivots=buildPivotQueries(subject,[...state.entities.values()]);for(const q of pivots){if(state.searchRequests>=LIMITS.maxSearchRequests)break;await investigateQuery(q,state,env,provider,d);}}
  const candidates=collectCandidates(state.entities,subject);const top=candidates[0]||null;return Response.json({status:"success",query:subject,subject,confidence:top?.confidence||0,summary:{candidates,people:candidates.filter(c=>c.name).map(c=>({value:c.name,score:c.confidence,sources:c.sources.length})),accounts:[...state.entities.values()].filter(e=>e.type==="account").sort((a,b)=>scoreEntity(b,subject)-scoreEntity(a,subject)).slice(0,15).map(e=>({type:"profile",platform:e.platform,username:e.username,url:e.sources[0]?.url,value:e.value,score:scoreEntity(e,subject),sources:e.sourceCount})),...mergeRelated(state.entities,subject)},evidence:[...state.entities.values()].filter(e=>e.sources.length).sort((a,b)=>scoreEntity(b,subject)-scoreEntity(a,subject)).slice(0,25).map(e=>({type:e.type,value:e.value,score:scoreEntity(e,subject),sources:e.sources.slice(0,5)})),sources:[...state.sources.values()],queryHistory:state.history,stats:{searchResults:state.history[0]?.resultCount||0,pagesRead:state.pagesRead,investigations:state.history.length,searchRequests:state.searchRequests,evidenceItems:state.entities.size,skippedSearches:state.skippedSearches.length,durationMs:Date.now()-started},skippedSearches:state.skippedSearches,limits:LIMITS,depth});}

export { investigate };
export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname==="/")return Response.json({name:"Free OSINT Explorer",status:"online",version:"0.6.0",endpoints:["/investigate"]});if(url.pathname==="/investigate"){try{return await investigate(request,env);}catch(error){return Response.json({status:"error",message:error.message||"Investigation failed"},{status:502});}}return Response.json({status:"error",error:"Not found"},{status:404});}};
