import { search } from "./search.js";

const LIMITS={maxSearchResults:5,maxPages:5,maxDepth:2,maxSearchRequests:5,maxCandidates:10,maxSourcesPerCandidate:10};
const PROFILE_HOSTS={"linkedin.com":"LinkedIn","my.linkedin.com":"LinkedIn","facebook.com":"Facebook","instagram.com":"Instagram","x.com":"X","twitter.com":"X","tiktok.com":"TikTok","youtube.com":"YouTube"};
const LOCATIONS=["Malaysia","Selangor","Kuala Lumpur","Terengganu","Kelantan","Johor","Penang","Perak","Pahang","Negeri Sembilan","Melaka","Sabah","Sarawak","Putrajaya","Labuan","Shah Alam","Petaling Jaya","Klang","Kota Bharu","Kuala Terengganu","Tumpat","Wakaf Bharu"];
const NOISE=new Set(["join","facebook","explore","email","password","login","bahasa","indonesia","messenger","lite","meta","photos","friends","connect","account","create","sign","up","home","about","contact","privacy","policy","terms","official","website","career","careers","business","commercial","division","head","executive","general","manager","profile","page","directory","malaysia","selangor","technology","services","certification","assistant","video","portfolio"]);
const normalize=v=>String(v||"").replace(/\s+/g," ").trim().toLowerCase();
const tokens=v=>normalize(v).split(/\s+/).filter(Boolean).filter(x=>x!=="bin"&&x!=="binti");
function likelyPerson(value,seed=""){const raw=String(value||"").trim(),ts=tokens(raw);if(ts.length<2||ts.length>6||raw.length<5||raw.length>90||ts.some(t=>NOISE.has(t)))return false;if(LOCATIONS.some(x=>normalize(x)===normalize(raw)))return false;const caps=raw.split(/\s+/).filter(w=>/^[A-ZÀ-Ý][a-zà-ÿ'-]+$/.test(w));if(caps.length<2)return false;const st=tokens(seed);return !st.length||ts.some(t=>st.includes(t));}
function entitiesFromText(text){const out=[],seen=new Set(),add=(type,value,confidence,evidence)=>{const v=String(value||"").trim(),key=`${type}:${normalize(v)}`;if(!v||seen.has(key))return;seen.add(key);out.push({type,value:v,normalized:normalize(v),confidence,evidence});};
for(const m of String(text||"").matchAll(/\b[A-ZÀ-Ý][a-zà-ÿ'-]+(?:\s+(?:bin|binti|[A-ZÀ-Ý][a-zà-ÿ'-]+)){1,5}\b/g)){if(likelyPerson(m[0]))add("person_candidate",m[0],/\b(bin|binti)\b/i.test(m[0])?.88:.62,"Name-like phrase found in page text");}
for(const m of String(text||"").matchAll(/\b[A-ZÀ-Ý][A-Za-zÀ-ÿ&.'-]*(?:\s+[A-ZÀ-Ý][A-Za-zÀ-ÿ&.'-]*){0,3}\s+(?:Berhad|Bhd|Sdn Bhd|Foundation|Association|University|Corporation|Company|Limited|Ltd)\b/g))add("organisation_candidate",m[0],.72,"Organisation-like phrase found in page text");
for(const location of LOCATIONS){if(new RegExp(`\\b${location.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}\\b`,"i").test(text))add("location_candidate",location,.84,"Known Malaysian location found in page text");}
for(const value of String(text||"").match(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi)||[])add("email",value,.99,"Email address pattern found in page text");
for(const value of String(text||"").match(/(?:\+?60[\s.-]?1[0-9][\s.-]?[0-9]{3,4}[\s.-]?[0-9]{3,4}|01[0-9][\s.-]?[0-9]{3,4}[\s.-]?[0-9]{3,4})/g)||[]){const n=value.replace(/\D/g,"");if(n.length>=10&&n.length<=12)add("phone",value,.90,"Malaysian phone number pattern found in page text");}
return out;}
function cleanUrl(url){try{const u=new URL(url);for(const k of ["utm_source","utm_medium","utm_campaign","utm_term","utm_content","msclkid"])u.searchParams.delete(k);return u.toString();}catch{return String(url||"");}}
function accountFromUrl(url,title=""){try{const u=new URL(url),host=u.hostname.toLowerCase().replace(/^www\./,""),platform=PROFILE_HOSTS[host];if(!platform)return null;const p=u.pathname.split("/").filter(Boolean);let username=null;if(platform==="LinkedIn")username=p[0]==="in"?p[1]:null;else if(platform==="YouTube")username=p[0]?.startsWith("@")?p[0].slice(1):(["channel","user","c"].includes((p[0]||"").toLowerCase())?p[1]:null);else username=p[0]?.startsWith("@")?p[0].slice(1):p[0];if(!username||["home","search","explore","login","signup","settings","directory","feed"].includes(username.toLowerCase()))return null;return{type:"account",platform,username,value:`${platform}: ${username}`,normalized:`${platform}:${username}`.toLowerCase(),confidence:normalize(title).includes(normalize(username))?.90:.75,url:cleanUrl(url)};}catch{return null;}}
function similarity(a,b){const x=tokens(a),y=tokens(b);if(!x.length||!y.length)return 0;const overlap=x.filter(t=>y.includes(t)).length,coverage=overlap/Math.max(x.length,y.length),surname=x.at(-1)===y.at(-1)?0.15:0;return Math.min(1,coverage*.75+surname);}
function score(e,subject){const sim=similarity(e.value,subject),exact=normalize(e.value)===normalize(subject)?1:0,multi=Math.min(1,e.sourceCount/3);return Number(Math.min(.95,(e.confidence||.5)*.35+sim*.30+multi*.25+exact*.10).toFixed(4));}
function addEvidence(entity,source,store){if(!entity?.type||!entity?.value)return;const key=`${entity.type}:${normalize(entity.normalized||entity.value)}`;let item=store.get(key);if(!item){item={...entity,normalized:normalize(entity.normalized||entity.value),sources:[],sourceCount:0};store.set(key,item);}if(!item.sources.some(s=>s.url===source.url)){item.sources.push({title:source.title||"",url:source.url,read:!!source.read});item.sourceCount++;}item.confidence=Math.max(item.confidence||0,entity.confidence||0);}
async function readPage(url){try{const target=new URL(url);if(!["http:","https:"].includes(target.protocol))throw new Error("Unsupported protocol");const r=await fetch(target.toString(),{headers:{"User-Agent":"Mozilla/5.0 (compatible; FreeOSINTExplorer/1.2)"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const html=await r.text();const title=(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim();const text=html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<nav[\s\S]*?<\/nav>/gi," ").replace(/<footer[\s\S]*?<\/footer>/gi," ").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim();return{ok:true,url:cleanUrl(target.toString()),title,textLength:text.length,entities:entitiesFromText(text)};}catch(error){return{ok:false,url,error:error.message||"Fetch failed"};}}
function pivotQueries(subject,store){const out=[],seen=new Set();const add=q=>{const k=normalize(q);if(!seen.has(k)){seen.add(k);out.push(q);}};for(const e of [...store.values()].filter(x=>x.type==="account").sort((a,b)=>b.sourceCount-a.sourceCount).slice(0,2))add(`"${subject}" ${e.platform}`);for(const e of [...store.values()].filter(x=>x.type==="organisation_candidate").sort((a,b)=>b.sourceCount-a.sourceCount).slice(0,2))add(`"${subject}" "${e.value}"`);return out.slice(0,3);}
export async function runInvestigation(subject,env={},provider=null,requestedDepth=1){const q=String(subject||"").trim();if(!q)throw new Error("Missing investigation query");const depth=Math.max(0,Math.min(LIMITS.maxDepth,Number(requestedDepth)||0));const state={visited:new Set(),searchRequests:0,pagesRead:0,entities:new Map(),sources:new Map(),failed:[],skippedSearches:[],history:[]},started=Date.now();
async function runQuery(query,currentDepth){if(state.visited.has(normalize(query))||state.searchRequests>=LIMITS.maxSearchRequests)return;state.visited.add(normalize(query));state.searchRequests++;let data;try{data=await search(query,env,provider);}catch(error){state.skippedSearches.push({query,depth:currentDepth,reason:error.message||"Search failed"});return;}const results=(data.results||[]).slice(0,LIMITS.maxSearchResults);for(const result of results){const source={title:result.title||"Search result",url:cleanUrl(result.url),read:false};for(const e of entitiesFromText(`${result.title||""}. ${result.snippet||""}`))if(e.type!=="person_candidate"||likelyPerson(e.value,result.title||""))addEvidence(e,source,state.entities);const account=accountFromUrl(result.url,result.title||"");if(account)addEvidence(account,source,state.entities);if(state.pagesRead>=LIMITS.maxPages)break;const page=await readPage(result.url);state.pagesRead++;if(!page.ok){state.failed.push({title:result.title||"",url:result.url,reason:page.error});continue;}const pageSource={title:page.title||result.title||"",url:page.url,read:true};for(const e of page.entities)if(e.type!=="person_candidate"||likelyPerson(e.value,page.title))addEvidence(e,pageSource,state.entities);const pageAccount=accountFromUrl(page.url,page.title);if(pageAccount)addEvidence(pageAccount,pageSource,state.entities);state.sources.set(page.url,{title:pageSource.title,url:page.url,status:200,textLength:page.textLength,read:true});}state.history.push({query,depth:currentDepth,resultCount:results.length,provider:data.provider||null});}
await runQuery(q,0);for(let d=1;d<=depth&&state.searchRequests<LIMITS.maxSearchRequests;d++){for(const pivot of pivotQueries(q,state.entities)){if(state.searchRequests>=LIMITS.maxSearchRequests)break;await runQuery(pivot,d);}}
const people=[...state.entities.values()].filter(e=>e.type==="person_candidate").map(e=>({...e,score:score(e,q)})).sort((a,b)=>b.score-a.score).slice(0,LIMITS.maxCandidates);const top=people[0]||null;const accounts=[...state.entities.values()].filter(e=>e.type==="account").map(e=>({...e,score:score(e,q)})).sort((a,b)=>b.score-a.score).slice(0,15);const related={organisations:[],locations:[],emails:[],phones:[]};for(const e of state.entities.values()){const group={organisation_candidate:"organisations",location_candidate:"locations",email:"emails",phone:"phones"}[e.type];if(group)related[group].push({value:e.value,confidence:score(e,q),sourceCount:e.sourceCount,sources:e.sources.slice(0,3)});}for(const key of Object.keys(related))related[key].sort((a,b)=>b.confidence-a.confidence).splice(10);
return{status:"success",query:q,subject:q,confidence:top?.score||0,summary:{candidates:people.map(e=>({id:e.id||null,name:e.value,confidence:e.score,sourceCount:e.sourceCount,sources:e.sources.slice(0,LIMITS.maxSourcesPerCandidate)})),accounts:accounts.map(e=>({platform:e.platform,username:e.username,url:e.url||e.sources[0]?.url||null,value:e.value,score:e.score,sources:e.sourceCount})),...related},evidence:[...state.entities.values()].filter(e=>e.sources.length).map(e=>({type:e.type,value:e.value,score:score(e,q),sourceCount:e.sourceCount,evidence:e.evidence,sources:e.sources.slice(0,5)})).sort((a,b)=>b.score-a.score).slice(0,40),sources:[...state.sources.values()],queryHistory:state.history,stats:{searchResults:state.history[0]?.resultCount||0,pagesRead:state.pagesRead,pagesFailed:state.failed.length,investigations:state.history.length,searchRequests:state.searchRequests,evidenceItems:state.entities.size,durationMs:Date.now()-started},failed:state.failed,skippedSearches:state.skippedSearches,limits:LIMITS,depth};}

export default runInvestigation;
