const SEARCH_USER_AGENT="Mozilla/5.0 (compatible; FreeOSINTExplorer/0.6)";
const DEFAULT_SEARXNG_URL="https://search.mectov.my.id";

function stripHtml(v){return String(v||"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim();}
function normalize(v){return String(v||"").toLowerCase().replace(/https?:\/\/[^\s]+/g," ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
function terms(q){return [...new Set(normalize(q).split(" ").filter(x=>x.length>=2))];}
function isNameLike(q){const t=terms(q);return t.length>=2&&t.length<=5&&t.every(x=>/^[a-z]+$/.test(x));}
function buildQueryVariants(q){q=String(q||"").trim();if(!isNameLike(q))return[q];const p=q.split(/\s+/);const out=[q,`"${q}"`];if(p.length===2&&!/\b(bin|binti)\b/i.test(q))out.push(`"${p[0]} bin ${p[1]}"`);return[...new Set(out)].slice(0,3);}
function score(r,q){const t=terms(q),title=normalize(r.title),snippet=normalize(r.snippet),tw=title.split(" "),sw=snippet.split(" ");const exact=title.includes(normalize(q));const tm=t.filter(x=>tw.includes(x)).length;const sm=t.filter(x=>!tw.includes(x)&&sw.includes(x)).length;let s=tm*.35+sm*.1,type="partial";if(exact){s=1;type="exact_phrase"}else if(tm===t.length){s=.9;type="all_terms_in_title"}else if(tm&&sm){s=.65;type="split_name"}else if(tm){s=.45;type="partial_title"}else if(sm){s=.2;type="snippet_only"}if(isNameLike(q)&&!exact&&tw.some(w=>t.some(x=>w.startsWith(x)&&w.length>x.length))){s=Math.min(s,.35);type="compound_name_partial"}if(snippet.includes(normalize(q))&&s<.75){s=Math.max(s,.55);type="exact_phrase_in_snippet"}return{score:s,matchType:type,matchedTerms:t.filter(x=>tw.includes(x)||sw.includes(x))};}
function rank(results,q){return results.map((r,i)=>{const x=score(r,q);return{...r,relevance:x.score,matchType:x.matchType,matchedTerms:x.matchedTerms,_i:i};}).filter(x=>x.relevance>0).sort((a,b)=>b.relevance-a.relevance||a._i-b._i).map(({_i,...r})=>r);}
function parseDDG(html){const out=[],seen=new Set();for(const block of html.split(/class=["']result(?:\s+results_links)?["']/i).slice(1)){if(/result--ad|captcha|bot/i.test(block))continue;const m=block.match(/class=["'][^"']*result__a[^"']*["'][^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/i)||block.match(/<a[^>]+href=["']([^"']+)["'][^>]+class=["'][^"']*result__a[^"']*["'][^>]*>([\s\S]*?)<\/a>/i);if(!m)continue;let u=m[1];try{const p=new URL(u.startsWith("//")?"https:"+u:u),d=p.searchParams.get("uddg");u=d?decodeURIComponent(d):p.toString();}catch{continue;}if(!/^https?:\/\//i.test(u)||seen.has(u))continue;seen.add(u);const sm=block.match(/class=["'][^"']*result__snippet[^"']*["'][^>]*>([\s\S]*?)<\/(?:a|div|span)>/i);out.push({title:stripHtml(m[2]),url:u,snippet:sm?stripHtml(sm[1]):""});}return out;}
function challenge(html){return /captcha|robot|unusual traffic|bot detection|challenge/i.test(String(html||""));}
async function duckduckgo(q){const attempts=["https://html.duckduckgo.com/html/","https://lite.duckduckgo.com/lite/"];let status=0,challenged=false;for(const url of attempts){const r=await fetch(url,{method:"POST",headers:{"User-Agent":SEARCH_USER_AGENT,"Accept":"text/html","Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({q}).toString()});const html=await r.text();status=r.status;if(!r.ok)continue;if(challenge(html)){challenged=true;continue;}const raw=parseDDG(html);if(raw.length)return{provider:"duckduckgo",query:q,results:rank(raw,q)};}if(challenged)throw new Error("DuckDuckGo challenge response");throw new Error(`Search provider returned ${status||"no"} usable results`);}
function searxUrl(base,q){const u=new URL(String(base||DEFAULT_SEARXNG_URL).replace(/\/+$/,""));u.pathname=u.pathname.replace(/\/$/,"")+"/search";u.searchParams.set("q",q);u.searchParams.set("format","json");u.searchParams.set("language","en");u.searchParams.set("categories","general");return u;}
async function searxng(q,env={}){const instances=[env.SEARXNG_URL||DEFAULT_SEARXNG_URL,env.SEARXNG_FALLBACK_URL].filter(Boolean);let last="";for(const instance of [...new Set(instances)].slice(0,2)){try{const r=await fetch(searxUrl(instance,q),{headers:{"User-Agent":SEARCH_USER_AGENT,"Accept":"application/json"}});const text=await r.text();if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=JSON.parse(text);const raw=(data.results||[]).map(x=>({title:stripHtml(x.title),url:String(x.url||x.link||""),snippet:stripHtml(x.content||x.snippet||"")})).filter(x=>/^https?:\/\//i.test(x.url));const results=rank(raw,q);if(results.length)return{provider:"searxng",instance,query:q,results};last=`${instance}: empty results`;}catch(e){last=`${instance}: ${e.message}`;}}throw new Error(`SearXNG failed: ${last}`);}
async function searchSingle(q,env={},provider=null){const p=String(provider||env.SEARCH_PROVIDER||"auto").toLowerCase();if(p==="duckduckgo")return duckduckgo(q);if(p==="searxng")return searxng(q,env);try{return{...(await duckduckgo(q)),attemptedProviders:["duckduckgo"]};}catch(e){const r=await searxng(q,env);return{...r,attemptedProviders:["duckduckgo:error:"+e.message,"searxng"]};}}
async function search(query,env={},requestedProvider=null){const variants=buildQueryVariants(query);if(variants.length===1)return searchSingle(query,env,requestedProvider);const merged=new Map(),attemptedQueries=[],attemptedProviders=[];for(const q of variants){try{const r=await searchSingle(q,env,requestedProvider);attemptedQueries.push(q);if(r.attemptedProviders)attemptedProviders.push(...r.attemptedProviders);for(const item of r.results||[]){const relevance=score(item,query).score;const value={...item,relevance:Math.max(item.relevance||0,relevance),queryVariant:q};const old=merged.get(item.url);if(!old||value.relevance>old.relevance)merged.set(item.url,value);}}catch{}}const results=[...merged.values()].sort((a,b)=>b.relevance-a.relevance).slice(0,5);if(!results.length)throw new Error("All search variants failed");return{provider:attemptedProviders.includes("searxng")?"searxng":"duckduckgo",query,results,attemptedProviders:[...new Set(attemptedProviders)],attemptedQueries,queryVariantCount:variants.length};}
export {search,duckduckgo,searxng,DEFAULT_SEARXNG_URL,buildQueryVariants};
